AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
